import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Undergraduate Researcher',
    company: 'Wang Bioinformatics Lab',
    company_legal_name: null,
    logo: '/images/education/riv.png',
    location: 'Riverside, California, USA',
    location_type: 'On-site',
    type: 'Part-time',
    start_date: '2024-01',
    end_date: null,
    industry: 'Bioinformatics',
    link: null,
    responsibilities: [
      'Developed a method for predicting MS3 fingerprints using CSI and SIRIUS',
      'Map fingerprints of MS3 spectra for each MS2 peak back to substructure fingerprint of original molecule',
      'Compare predicted fingerprint to known fingerprint of SMILEs of MS2 precursor ion, which can help determine the substructure of the MS3 precursor ion',
    ],
    skills: [
      'Python (Programming Language)',
      'Research',
      'Machine Learning',
      'AI Software Development',
    ],
  },
  // {
  //   "position": "Undergraduate Researcher",
  //   "company": "Wang Bioinformatics Lab",
  //   "company_legal_name": "Wang Bioinformatics Lab",
  //   "logo": null,
  //   "location": "Riverside, California, USA",
  //   "location_type": "On-site",
  //   "type": "Part-time",
  //   "start_date": "2023-09",
  //   "end_date": "2024-01",
  //   "industry": "Bioinformatics",
  //   "link": null,
  //   "responsibilities": [
  //     "Optimize and benchmark the quantum simulation of tandem mass spectrometry data",
  //     "Enhance Nextflow Pipeline to run Quantum Simulation software QCXMS to efficiently allocate resources on Cluster",
  //     "Change QCXMS source code to short cut simulation time",
  //     "Consistently follow/meet up with supervising instructor during project implementation to discuss progress and demo things if needed",
  //     "Assess changes to accuracy compared to experimental data with above changes"
  //   ],
  //   "skills": [
  //     "Clean Coding",
  //     "Performance Tuning",
  //     "Demos",
  //     "Web Conferencing",
  //     "Optimization",
  //     "Analytical Skills"
  //   ]
  // },
  // {
  //   "position": "Undergraduate Researcher",
  //   "company": "Wang Bioinformatics Lab",
  //   "company_legal_name": "Wang Bioinformatics Lab",
  //   "logo": null,
  //   "location": "Riverside, California, USA",
  //   "location_type": "On-site",
  //   "type": "Part-time",
  //   "start_date": "2023-04",
  //   "end_date": "2023-11",
  //   "industry": "Bioinformatics",
  //   "link": null,
  //   "responsibilities": [
  //     "Created a workflow to summarize peak distributions of public metabolomics mass spectrometry data",
  //     "Developed Python scripts to process a large volume of files and generate individual heatmaps for analysis",
  //     "Merged heatmaps efficiently to facilitate peak analysis and gain insights",
  //     "Utilized Nextflow workflow properties for efficient parallel processing of the heatmap creation and analysis tasks"
  //   ],
  //   "skills": [
  //     "Performance Tuning",
  //     "Optimization"
  //   ]
  // },
  // {
  //   "position": "Computer Science Grader",
  //   "company": "University of California, Riverside",
  //   "company_legal_name": "University of California, Riverside",
  //   "logo": null,
  //   "location": "Riverside, California, USA",
  //   "location_type": "On-site",
  //   "type": "Full-time",
  //   "start_date": "2025-01",
  //   "end_date": "2025-05",
  //   "industry": "Education",
  //   "link": null,
  //   "responsibilities": [
  //     "Grade coursework (homeworks and exams) for 150+ students for the Intermediate Data Structures and Algorithms class (CS141)"
  //   ],
  //   "skills": []
  // },
  // {
  //   "position": "Computer Science Grader",
  //   "company": "University of California, Riverside",
  //   "company_legal_name": "University of California, Riverside",
  //   "logo": null,
  //   "location": "Riverside, California, USA",
  //   "location_type": "On-site",
  //   "type": "Full-time",
  //   "start_date": "2024-01",
  //   "end_date": "2025-05",
  //   "industry": "Education",
  //   "link": null,
  //   "responsibilities": [
  //     "Grade coursework (homeworks and exams) for 60+ students for the Introduction to Machine Learning class (CS171)"
  //   ],
  //   "skills": []
  // },
  {
    position: 'Computer Science Grader',
    company: 'University of California, Riverside',
    company_legal_name: null,
    logo: '/images/education/riv.png',
    location: 'Riverside, California, USA',
    location_type: 'On-site',
    type: null,
    start_date: '2023-09',
    end_date: '2025-05',
    industry: 'Education',
    link: null,
    responsibilities: [
      'Grade coursework (homeworks and exams) for 60+ students for the Introduction to Machine Learning class (CS171)',
      'Grade coursework (homeworks and exams) for 150+ students for the Intermediate Data Structures and Algorithms class(CS141)',
      'Grade coding assignments and set competitive coding style problems as well as answer doubts or questions for CS119L (Algorithmic Programming and Problem Solving)',
    ],
    skills: [],
  },
  // {
  //   "position": "Computer Science Grader",
  //   "company": "University of California, Riverside",
  //   "company_legal_name": "University of California, Riverside",
  //   "logo": null,
  //   "location": "Riverside, California, USA",
  //   "location_type": "On-site",
  //   "type": "Part-time",
  //   "start_date": "2023-09",
  //   "end_date": "2023-12",
  //   "industry": "Education",
  //   "link": null,
  //   "responsibilities": [
  //     "Reader for CS119L (Algorithmic Programming and Problem Solving)"
  //   ],
  //   "skills": []
  // },
  {
    position: 'Software Engineering Intern',
    company: 'Harbinger Motors',
    company_legal_name: null,
    logo: '/images/careers/harbinger.png',
    location: 'Garden Grove, California, USA',
    location_type: 'On-site',
    type: 'Full-time',
    start_date: '2024-06',
    end_date: '2024-09',
    industry: 'Automotive',
    link: 'https://harbingermotors.com',
    responsibilities: [
      'Develop an IPC display system that processes and visualizes over 300 CAN signals from various ECUs, enhancing interface functionality and user experience',
      'Ensure compliance with FMVSS standards by integrating standardized icons and implementing bulb checks',
      'Design and implement a centralized UDS service for flashing and diagnostic over CAN and Ethernet while abstracting communication protocols for the user',
      'Engineer an inhouse tool that uses the UDS service to allow seamless ECU flashing and diagnostics from a GUI',
      'Achieve a 20% improvement in memory usage and reduce runtime through object-oriented programming techniques',
      'Leverage Docker to run Linux-compiled seed-key algorithms natively on Windows, improving cross-platform compatibility and operational efficiency',
      'Help in the development and testing of ECU flashing via VCU routing of package data',
      'Develop a proof of concept (PoC) for a new vehicle display system, utilizing Structured Text and Free Body Diagrams, completing the project within 3 weeks',
    ],
    skills: ['Clean Coding', 'Demos', 'Web Conferencing', 'Embedded Systems'],
  },
  {
    position: 'Machine Learning Intern',
    company: 'Excellon Software',
    company_legal_name: null,
    logo: '/images/careers/excellon.png',
    location: 'Pune, India',
    location_type: 'On-site',
    type: 'Full-time',
    start_date: '2023-07',
    end_date: '2023-09',
    industry: 'Software Development',
    link: null,
    responsibilities: [
      'Developed versatile and generic pipeline for ETL, and ML tasks with advanced features and model techniques',
      'Leveraged MLFlow properties for efficient model tracking and maintenance',
      'Engineered effective ML solutions for complex forecasting tasks, achieving robust results through tailored algorithms and ensemble techniques',
      'Researched and utilized various libraries such as scikit-learn and PyCaret for automation of ML tasks',
      'Built generic API to ingest data from various sources, reducing 10+ hours of manual work',
      'Optimized models by efficient hyper-parameter optimization techniques such as Tree-Parzen Estimations to improve training time by up to 30%',
      "Helped initiate the development of a voice-activated method for executing user-defined commands using OpenAI's whisper library, which provides support for over 10+ languages",
    ],
    skills: [
      'Clean Coding',
      'MLOps',
      'APIs',
      'Problem Solving',
      'MLflow',
      'Machine Learning',
      'Performance Tuning',
      'AI Software Development',
      'PyTorch',
      'Data Science',
      'Web Conferencing',
      'Optimization',
      'Data Analysis',
      'Analytical Skills',
      'Docker',
      'Automated Machine Learning (AutoML)',
    ],
  },
  {
    position: 'Software Engineer',
    company: 'Engineers for Good',
    company_legal_name: null,
    logo: null,
    location: 'Riverside, California, USA',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2022-11',
    end_date: '2023-06',
    industry: 'Non-profit',
    link: null,
    responsibilities: [
      'Work with a team of developers to build an applicant tracking software and database with Microsoft Power Apps for a non-profit animal shelter organization',
      'Use Dataverse to create views to query 500+ organization records and 1000+ Person records',
      'Integrate Dataverse with Power Pages to provide easier-to-access updates on candidates progress reducing 10+ hours of manual work per week',
    ],
    skills: ['Clean Coding', 'Demos', 'Web Conferencing'],
  },
];
