import { CareerProps } from '../types/careers';

export const VOLUNTEERING: CareerProps[] = [
  {
    position: 'Captain',
    company: 'UCR Mens Tennis',
    company_legal_name: 'University of California, Riverside',
    logo: null,
    location: 'Riverside, California, USA',
    location_type: 'On-site',
    type: 'Part-time',
    start_date: '2024-08',
    end_date: '2025-06',
    industry: 'Sports',
    link: null,
    responsibilities: [],
    skills: [],
  },
  {
    position: 'Driver Interface Lead',
    company: 'UCR Solar Car',
    company_legal_name: 'University of California, Riverside',
    logo: null,
    location: 'Riverside, California, USA',
    location_type: 'On-site',
    type: 'Part-time',
    start_date: '2022-11',
    end_date: '2025-05',
    industry: 'Automotive',
    link: null,
    responsibilities: [
      'Manage 8+ developer team to create and maintain driver interface with QT C++ to display realtime vehicle information and manage vitals',
      'Help integrate PiWiring to allow for electrical interfacing to receive inputs from actuators to trigger QT Slots and Signals',
      'Help engineer wireless telemetry to handle 120+ payloads per minute to display analytics through InfluxDB & Grafana',
    ],
    skills: ['Clean Coding', 'Demos', 'Web Conferencing', 'Embedded Systems'],
  },
  {
    position: 'Driver Interface Engineer',
    company: 'UCR Solar Car',
    company_legal_name: 'University of California, Riverside',
    logo: null,
    location: 'Riverside, California, USA',
    location_type: 'On-site',
    type: 'Part-time',
    start_date: '2022-07',
    end_date: '2024-08',
    industry: 'Automotive',
    link: null,
    responsibilities: [
      'Automate conditional compilation upon Raspberry Pi boot with custom bootup removing 2+ minutes of manual labor',
      'Scale & dynamically position 20+ GUI widgets to be responsive to prevent production irregularities',
      'Created bootup checks to make sure all vital signs are working normally',
      'Architect classes to be more efficient and reduce memory usage by 20%',
      'Created tire pressure system to indicate condition of tires',
    ],
    skills: ['Qt', 'C++', 'Qt Creator', 'Git', 'Embedded Systems'],
  },
  {
    position: 'Secretary',
    company: 'ACM@UCR',
    company_legal_name: 'ACM@UCR',
    logo: null,
    location: 'Riverside, California, USA',
    location_type: 'On-site',
    type: 'Part-time',
    start_date: '2023-03',
    end_date: '2024-04',
    industry: 'Professional Association',
    link: null,
    responsibilities: [
      'Look after membership management and engagement with the global ACM chapter',
      'Logistics coordination for events and ensuring smooth operations',
      'Handling backend operations and administrative tasks',
    ],
    skills: ['Team Leadership', 'Organizational Leadership'],
  },
];
